import type { Config } from "tailwindcss";

const config: Config = {
	darkMode: "selector",
	content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
	theme: {
		extend: {
			colors: {
				// Semantic color aliases
				bg: "var(--color-bg)",
				"bg-muted": "var(--color-bg-muted)",
				surface: "var(--color-surface)",
				"surface-hover": "var(--color-surface-hover)",
				"surface-active": "var(--color-surface-active)",
				border: "var(--color-border)",
				"border-hover": "var(--color-border-hover)",
				"border-strong": "var(--color-border-strong)",
				"surface-contrast": "var(--color-surface-contrast)",
				"surface-contrast-hover": "var(--color-surface-contrast-hover)",
				"fg-muted": "var(--color-fg-muted)",
				fg: "var(--color-fg)",
				info: "var(--color-info)",
				success: "var(--color-success)",
				warning: "var(--color-warning)",
				danger: "var(--color-danger)",
				brand: "var(--color-brand)",

				// Design system color scales
				gray: {
					1: "var(--ds-gray-1)",
					2: "var(--ds-gray-2)",
					3: "var(--ds-gray-3)",
					4: "var(--ds-gray-4)",
					5: "var(--ds-gray-5)",
					6: "var(--ds-gray-6)",
					7: "var(--ds-gray-7)",
					8: "var(--ds-gray-8)",
					9: "var(--ds-gray-9)",
					10: "var(--ds-gray-10)",
				},
				"gray-alpha": {
					1: "var(--ds-gray-alpha-1)",
					2: "var(--ds-gray-alpha-2)",
					3: "var(--ds-gray-alpha-3)",
					4: "var(--ds-gray-alpha-4)",
					5: "var(--ds-gray-alpha-5)",
					6: "var(--ds-gray-alpha-6)",
					7: "var(--ds-gray-alpha-7)",
					8: "var(--ds-gray-alpha-8)",
					9: "var(--ds-gray-alpha-9)",
					10: "var(--ds-gray-alpha-10)",
				},
				blue: {
					1: "var(--ds-blue-1)",
					2: "var(--ds-blue-2)",
					3: "var(--ds-blue-3)",
					4: "var(--ds-blue-4)",
					5: "var(--ds-blue-5)",
					6: "var(--ds-blue-6)",
					7: "var(--ds-blue-7)",
					8: "var(--ds-blue-8)",
					9: "var(--ds-blue-9)",
					10: "var(--ds-blue-10)",
				},
				red: {
					1: "var(--ds-red-1)",
					2: "var(--ds-red-2)",
					3: "var(--ds-red-3)",
					4: "var(--ds-red-4)",
					5: "var(--ds-red-5)",
					6: "var(--ds-red-6)",
					7: "var(--ds-red-7)",
					8: "var(--ds-red-8)",
					9: "var(--ds-red-9)",
					10: "var(--ds-red-10)",
				},
				amber: {
					1: "var(--ds-amber-1)",
					2: "var(--ds-amber-2)",
					3: "var(--ds-amber-3)",
					4: "var(--ds-amber-4)",
					5: "var(--ds-amber-5)",
					6: "var(--ds-amber-6)",
					7: "var(--ds-amber-7)",
					8: "var(--ds-amber-8)",
					9: "var(--ds-amber-9)",
					10: "var(--ds-amber-10)",
				},
				green: {
					1: "var(--ds-green-1)",
					2: "var(--ds-green-2)",
					3: "var(--ds-green-3)",
					4: "var(--ds-green-4)",
					5: "var(--ds-green-5)",
					6: "var(--ds-green-6)",
					7: "var(--ds-green-7)",
					8: "var(--ds-green-8)",
					9: "var(--ds-green-9)",
					10: "var(--ds-green-10)",
				},
				teal: {
					1: "var(--ds-teal-1)",
					2: "var(--ds-teal-2)",
					3: "var(--ds-teal-3)",
					4: "var(--ds-teal-4)",
					5: "var(--ds-teal-5)",
					6: "var(--ds-teal-6)",
					7: "var(--ds-teal-7)",
					8: "var(--ds-teal-8)",
					9: "var(--ds-teal-9)",
					10: "var(--ds-teal-10)",
				},
				purple: {
					1: "var(--ds-purple-1)",
					2: "var(--ds-purple-2)",
					3: "var(--ds-purple-3)",
					4: "var(--ds-purple-4)",
					5: "var(--ds-purple-5)",
					6: "var(--ds-purple-6)",
					7: "var(--ds-purple-7)",
					8: "var(--ds-purple-8)",
					9: "var(--ds-purple-9)",
					10: "var(--ds-purple-10)",
				},
				pink: {
					1: "var(--ds-pink-1)",
					2: "var(--ds-pink-2)",
					3: "var(--ds-pink-3)",
					4: "var(--ds-pink-4)",
					5: "var(--ds-pink-5)",
					6: "var(--ds-pink-6)",
					7: "var(--ds-pink-7)",
					8: "var(--ds-pink-8)",
					9: "var(--ds-pink-9)",
					10: "var(--ds-pink-10)",
				},
			},
			fontSize: {
				xs: ["var(--text-xs)", { lineHeight: "var(--text-xs-line-height)" }],
				sm: ["var(--text-sm)", { lineHeight: "var(--text-sm-line-height)" }],
				base: [
					"var(--text-base)",
					{ lineHeight: "var(--text-base-line-height)" },
				],
				lg: ["var(--text-lg)", { lineHeight: "var(--text-lg-line-height)" }],
				xl: ["var(--text-xl)", { lineHeight: "var(--text-xl-line-height)" }],
				"2xl": [
					"var(--text-2xl)",
					{ lineHeight: "var(--text-2xl-line-height)" },
				],
				"3xl": [
					"var(--text-3xl)",
					{ lineHeight: "var(--text-3xl-line-height)" },
				],
				"4xl": [
					"var(--text-4xl)",
					{ lineHeight: "var(--text-4xl-line-height)" },
				],
				"5xl": [
					"var(--text-5xl)",
					{ lineHeight: "var(--text-5xl-line-height)" },
				],
			},
			fontFamily: {
				sans: "var(--font-sans)",
				mono: "var(--font-mono)",
			},
			fontWeight: {
				normal: "var(--font-weight-normal)",
				medium: "var(--font-weight-medium)",
				semibold: "var(--font-weight-semibold)",
				bold: "var(--font-weight-bold)",
			},
			letterSpacing: {
				tighter: "var(--tracking-tighter)",
				tight: "var(--tracking-tight)",
				wide: "var(--tracking-wide)",
				widest: "var(--tracking-widest)",
			},
			spacing: {
				unit: "var(--spacing-unit)",
			},
			borderRadius: {
				xs: "var(--radius-xs)",
				sm: "var(--radius-sm)",
				md: "var(--radius-md)",
				lg: "var(--radius-lg)",
				xl: "var(--radius-xl)",
				"2xl": "var(--radius-2xl)",
				full: "var(--radius-full)",
			},
			transitionDuration: {
				75: "var(--duration-75)",
				100: "var(--duration-100)",
				150: "var(--duration-150)",
				200: "var(--duration-200)",
				300: "var(--duration-300)",
				500: "var(--duration-500)",
				700: "var(--duration-700)",
				1000: "var(--duration-1000)",
			},
			transitionTimingFunction: {
				in: "var(--ease-in)",
				out: "var(--ease-out)",
				"in-out": "var(--ease-in-out)",
			},
			keyframes: {
				hide: {
					from: { opacity: "1" },
					to: { opacity: "0" },
				},
				slideDownAndFade: {
					from: { opacity: "0", transform: "translateY(-6px)" },
					to: { opacity: "1", transform: "translateY(0)" },
				},
				slideLeftAndFade: {
					from: { opacity: "0", transform: "translateX(6px)" },
					to: { opacity: "1", transform: "translateX(0)" },
				},
				slideUpAndFade: {
					from: { opacity: "0", transform: "translateY(6px)" },
					to: { opacity: "1", transform: "translateY(0)" },
				},
				slideRightAndFade: {
					from: { opacity: "0", transform: "translateX(-6px)" },
					to: { opacity: "1", transform: "translateX(0)" },
				},
				dialogOverlayShow: {
					from: { opacity: "0" },
					to: { opacity: "1" },
				},
				dialogContentShow: {
					from: {
						opacity: "0",
						transform: "translate(-50%, -45%) scale(0.95)",
					},
					to: { opacity: "1", transform: "translate(-50%, -50%) scale(1)" },
				},
				drawerSlideLeftAndFade: {
					from: { opacity: "0", transform: "translateX(50%)" },
					to: { opacity: "1", transform: "translateX(0)" },
				},
			},
			animation: {
				hide: "hide 150ms cubic-bezier(0.16, 1, 0.3, 1)",
				slideDownAndFade:
					"slideDownAndFade 150ms cubic-bezier(0.16, 1, 0.3, 1)",
				slideLeftAndFade:
					"slideLeftAndFade 150ms cubic-bezier(0.16, 1, 0.3, 1)",
				slideUpAndFade: "slideUpAndFade 150ms cubic-bezier(0.16, 1, 0.3, 1)",
				slideRightAndFade:
					"slideRightAndFade 150ms cubic-bezier(0.16, 1, 0.3, 1)",
				drawerSlideLeftAndFade:
					"drawerSlideLeftAndFade 150ms cubic-bezier(0.16, 1, 0.3, 1)",
				dialogOverlayShow:
					"dialogOverlayShow 150ms cubic-bezier(0.16, 1, 0.3, 1)",
				dialogContentShow:
					"dialogContentShow 150ms cubic-bezier(0.16, 1, 0.3, 1)",
			},
		},
	},
	plugins: [require("@tailwindcss/forms")],
};
export default config
